import { ImageSourcePropType } from 'react-native';
import { Freshness } from '../types';

// Generated by scripts/build-markers.mjs. React Native picks the @2x/@3x variant for the screen.

/** Map marker images, keyed by the Mapbox image id used in the symbol layer. */
export const MAP_MARKER_IMAGES: Record<`marker-${Freshness}`, ImageSourcePropType> = {
  'marker-never': require('../../assets/markers/marker-never.png'),
  'marker-fresh': require('../../assets/markers/marker-fresh.png'),
  'marker-recent': require('../../assets/markers/marker-recent.png'),
  'marker-old': require('../../assets/markers/marker-old.png'),
};

/** 60x80 dp markers for cards and the detail panel. */
export const LARGE_MARKER_IMAGES: Record<Freshness, ImageSourcePropType> = {
  never: require('../../assets/markers/marker-large-never.png'),
  fresh: require('../../assets/markers/marker-large-fresh.png'),
  recent: require('../../assets/markers/marker-large-recent.png'),
  old: require('../../assets/markers/marker-large-old.png'),
};
